site_name: 'netschoolapi'
site_description: 'Документация netschoolapi'
site_author: 'Иван Горланов'
copyright: 'Даниил Николаев, Иван Горланов'

repo_url: 'https://github.com/nm17/netschoolapi'
repo_name: 'netschoolapi'

markdown_extensions:
  - admonition
  - attr_list

nav:
  - 'netschoolapi': 'index.md'

theme: 'readthedocs'

extra:
  version: 0.0.1